{{/* Database Secret */}}
{{- if not .Values.secrets.database.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "noah-loop.databaseSecretName" . }}
  labels:
    {{- include "noah-loop.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.database.username }}
  {{ .Values.secrets.database.existingSecretUsernameKey }}: {{ .Values.secrets.database.username | b64enc }}
  {{- end }}
  {{- if .Values.secrets.database.password }}
  {{ .Values.secrets.database.existingSecretPasswordKey }}: {{ .Values.secrets.database.password | b64enc }}
  {{- end }}
{{- end }}

{{/* Redis Secret */}}
{{- if and .Values.secrets.redis.password (not .Values.secrets.redis.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "noah-loop.redisSecretName" . }}
  labels:
    {{- include "noah-loop.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secrets.redis.existingSecretPasswordKey }}: {{ .Values.secrets.redis.password | b64enc }}
{{- end }}

{{/* App Secret */}}
{{- if not .Values.secrets.app.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "noah-loop.appSecretName" . }}
  labels:
    {{- include "noah-loop.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.app.jwtSecret }}
  jwt-secret: {{ .Values.secrets.app.jwtSecret | b64enc }}
  {{- end }}
  {{- if .Values.secrets.app.apiKey }}
  api-key: {{ .Values.secrets.app.apiKey | b64enc }}
  {{- end }}
{{- end }}
