{{/* API Gateway Service */}}
{{- if .Values.apiGateway.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "noah-loop.fullname" . }}-api-gateway
  labels:
    {{- include "noah-loop.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
spec:
  type: {{ .Values.apiGateway.service.type }}
  ports:
    - port: {{ .Values.apiGateway.service.port }}
      targetPort: {{ .Values.apiGateway.service.targetPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.apiGateway.service.grpcPort }}
      targetPort: {{ .Values.apiGateway.service.grpcTargetPort }}
      protocol: TCP
      name: grpc
  selector:
    {{- include "noah-loop.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
{{- end }}

{{/* 微服务 Service 模板 */}}
{{- range $serviceName, $service := .Values.services }}
{{- if $service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "noah-loop.fullname" $ }}-{{ $serviceName }}
  labels:
    {{- include "noah-loop.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
spec:
  type: {{ $service.service.type }}
  ports:
    - port: {{ $service.service.port }}
      targetPort: {{ $service.service.targetPort }}
      protocol: TCP
      name: http
    - port: {{ $service.service.grpcPort }}
      targetPort: {{ $service.service.grpcTargetPort }}
      protocol: TCP
      name: grpc
  selector:
    {{- include "noah-loop.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
{{- end }}
{{- end }}
