# Noah-Loop Docker环境配置文件
# 适用于容器化部署

app:
  name: "noah-loop"
  version: "1.0.0"
  environment: "production"
  debug: false

http:
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"
  shutdown_timeout: "30s"

grpc:
  port: 9090

# Docker环境下的服务端口配置（内部端口）
services:
  agent:
    port: 8081
    grpc_port: 9091
  
  llm:
    port: 8082
    grpc_port: 9092
  
  mcp:
    port: 8083
    grpc_port: 9093
  
  orchestrator:
    port: 8084
    grpc_port: 9094

database:
  host: "postgres"  # Docker服务名
  port: 5432
  user: "postgres"
  password: "postgres"
  database: "noah_loop_db"
  sslmode: "disable"
  max_open_conns: 25
  max_idle_conns: 10
  max_lifetime: "5m"

redis:
  addr: "redis:6379"  # Docker服务名
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5
  dial_timeout: "5s"
  read_timeout: "3s"
  write_timeout: "3s"

log:
  level: "info"
  format: "json"
